<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>Latest</LangVersion>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Arc.Graphics\Arc.Graphics.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Vortice.D3DCompiler" Version="3.8.2" />
      <PackageReference Include="Vortice.Direct3D11" Version="3.8.2" />
      <PackageReference Include="Vortice.DXGI" Version="3.8.2" />
    </ItemGroup>

</Project>
