using System.CodeDom.Compiler;
using System.Collections.Immutable;
using System.Runtime.CompilerServices;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Arc.Ecs.SourceGen;

public readonly record struct TargetComponent
{
    public readonly string Namespace;
    public readonly string Name;
    public readonly bool IsReferenceType;

    public string FullName => $"{Namespace}{(string.IsNullOrEmpty(Namespace) ? "" : ".")}{Name}";

    public TargetComponent(string @namespace, string name, bool isReferenceType)
    {
        Namespace = @namespace;
        Name = name;
        IsReferenceType = isReferenceType;
    }
}

[Generator(LanguageNames.CSharp)]
public class ComponentRegistrationGenerator : IIncrementalGenerator
{
    private const string Namespace = "Arc.Ecs";
    private const string ComponentAttributeName = "ComponentAttribute";
    private const string ComponentAttributeFullName = $"{Namespace}.{ComponentAttributeName}";

    private const string AttributeSourceCode = $@"// <auto-generated/>

namespace {Namespace};

[System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Struct)]
public class {ComponentAttributeName} : System.Attribute
{{
    public string Name {{ get; set; }} = string.Empty;
}}
";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Add the marker attribute to the compilation.
        context.RegisterPostInitializationOutput(static ctx =>
            {
                ctx.AddEmbeddedAttributeDefinition();
                ctx.AddSource(
                    "Arc.Ecs.Generated.ComponentAttribute.g.cs",
                    SourceText.From(AttributeSourceCode, Encoding.UTF8)
                );
            }
        );

        // Filter classes annotated with the [Component] attribute. Only filtered Syntax Nodes can trigger code generation.
        var targetComponents = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                ComponentAttributeFullName,
                predicate: (node, _) => node is ClassDeclarationSyntax or StructDeclarationSyntax,
                transform: static (ctx, _) => GetTargetToGen(ctx)
            )
            .Where(static m => m is not null)
            .Select(static (t, _) => t!.Value);

        // Generate the source code.
        context.RegisterSourceOutput(
            targetComponents.Collect(),
            static (ctx, t) => Execute(ctx, t)
        );
    }

    private static string GetFullNamespace(INamespaceSymbol? ns)
    {
        if (ns is null || ns.IsGlobalNamespace) return string.Empty;

        var stack = new Stack<string>();
        while (ns is { IsGlobalNamespace: false })
        {
            stack.Push(ns.Name);
            ns = ns.ContainingNamespace;
        }

        return string.Join(".", stack);
    }

    private static TargetComponent? GetTargetToGen(GeneratorAttributeSyntaxContext ctx)
    {
        var semanticModel = ctx.SemanticModel;
        var declSyntax = ctx.TargetNode;

        // Get the semantic representation of the struct/class syntax
        if (semanticModel.GetDeclaredSymbol(declSyntax) is not INamedTypeSymbol typeSymbol)
        {
            // Something went wrong
            return null;
        }

        var @namespace = GetFullNamespace(typeSymbol.ContainingNamespace);

        // Get the full type name of the class e.g. Mesh
        // our OuterClass<T>.Mesh if it was nested in a generic type (for example)
        var className = typeSymbol.Name;
        Unsafe.SizeOf<int>();
        return new TargetComponent(@namespace, className, typeSymbol.IsReferenceType);
    }

    private static void Execute(SourceProductionContext ctx, ImmutableArray<TargetComponent> targetComponents)
    {
        /*if (targetComponent is { } value)
        {
            // Generate the source code and add it to the output
            var result = SourceGenerationHelper.GenerateSerializablePartialClass(value);
            // Create a separate partial class file for each Serializable
            ctx.AddSource($"Serializable.{value.Name}.g.cs", result);
        }*/

        using var sw = new StringWriter();
        using IndentedTextWriter writer = new(sw);

        writer.Indent = 0;
        writer.WriteLine("// <auto-generated/>");
        writer.WriteLine("using System.Runtime.CompilerServices;");
        writer.WriteLine();

        writer.WriteLine("namespace Arc.Ecs.Generated;");
        writer.WriteLine();
        writer.WriteLine("internal static partial class ComponentRegistryBootstrap");
        writer.WriteLine("{");
        writer.Indent++;
        // ComponentTypeInfo for each component
        writer.WriteLine($"// {targetComponents.Length} generated components");
        foreach (var targetComponent in targetComponents)
        {
            var id = Utility.ComputeHash(targetComponent.FullName);
            writer.WriteLine($"public static readonly ComponentTypeInfo {targetComponent.Name} = new(");
            writer.Indent++;
            writer.WriteLine($"Id: {id},");
            writer.WriteLine($"ManagedType: typeof({targetComponent.FullName}),");
            writer.WriteLine($"Size: (uint)Unsafe.SizeOf<{targetComponent.FullName}>(),");
            writer.WriteLine($"ContainsRefs: {targetComponent.IsReferenceType.ToString().ToLowerInvariant()},");
            writer.WriteLine($"IsTag: Unsafe.SizeOf<{targetComponent.FullName}>() <= 1,");
            writer.WriteLine($"BitIndex: 0"); // Will be set automatically
            writer.Indent--;
            writer.WriteLine(");");
        }
        writer.WriteLine();
        writer.WriteLine("public static void RegisterAll()");
        writer.WriteLine("{");
        writer.Indent++;
        // Call Register(...) for each component
        foreach (var targetComponent in targetComponents)
        {
            writer.WriteLine($"global::Arc.Ecs.ComponentRegistry.Register({targetComponent.Name});");
        }
        writer.Indent--;
        writer.WriteLine("}");
        writer.WriteLine();
        writer.WriteLine("[System.Runtime.CompilerServices.ModuleInitializer]");
        writer.WriteLine("internal static void Initialize() => RegisterAll();");

        writer.Indent--;
        writer.WriteLine("}");

        var resultSource = sw.ToString();
        ctx.AddSource($"Arc.Ecs.Generated.ComponentRegistryBootstrap.g.cs", resultSource);
    }
}