using System.CodeDom.Compiler;
using Microsoft.CodeAnalysis;

namespace Arc.Ecs.SourceGen;

[Generator(LanguageNames.CSharp)]
public class QueryGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Emit queries ONLY when compiling Arc.Ecs assembly
        var isArcEcs = context.CompilationProvider.Select(static (compilation, _) => string.Equals(
                compilation.AssemblyName, "Arc.Ecs", StringComparison.Ordinal
            )
        );

        // Generate the source code.
        for (var arity = 2; arity < 5; ++arity)
        {
            var arityCount = arity;

            context.RegisterSourceOutput(
                isArcEcs, (spc, emit) =>
                {
                    if (!emit)
                        return;

                    ExecuteQueryGen(spc, arityCount);
                    ExecuteWorldGen(spc, arityCount);
                }
            );
        }
    }

    private static void ExecuteQueryGen(SourceProductionContext ctx, int arity)
    {
        using var sw = new StringWriter();
        using IndentedTextWriter writer = new(sw);

        writer.Indent = 0;
        writer.WriteLine("// <auto-generated/>");
        writer.WriteLine();
        writer.WriteLine("namespace Arc.Ecs;");
        writer.WriteLine();
        ForEachDelegates(writer, arity);
        writer.WriteLine();
        writer.WriteLine($"public class Query<{GenericArgs(arity)}> : QueryBase<Query<{GenericArgs(arity)}>>");
        writer.WriteLine("{");
        writer.Indent++;
        Ctor(writer);
        writer.WriteLine();
        ForEach(writer, arity);
        writer.WriteLine();
        ForEachEntity(writer, arity);
        writer.Indent--;
        writer.WriteLine("}");
        var resultSource = sw.ToString();
        ctx.AddSource($"Arc.Ecs.Query.{arity}.g.cs", resultSource);
    }

    private static void ExecuteWorldGen(SourceProductionContext ctx, int arity)
    {
        using var sw = new StringWriter();
        using IndentedTextWriter writer = new(sw);

        writer.Indent = 0;
        writer.WriteLine("// <auto-generated/>");
        writer.WriteLine();
        writer.WriteLine("namespace Arc.Ecs;");
        writer.WriteLine();
        writer.WriteLine($"public static class WorldExtensions{arity}");
        writer.WriteLine("{");
        writer.Indent++;
        writer.WriteLine($"public static Query<{GenericArgs(arity)}> Query<{GenericArgs(arity)}>(this World world) => new(world);");
        writer.Indent--;
        writer.WriteLine("}");
        var resultSource = sw.ToString();
        ctx.AddSource($"Arc.Ecs.WorldQuery.{arity}.g.cs", resultSource);
    }

    private static void ForEachDelegates(IndentedTextWriter writer, int arity)
    {
        writer.WriteLine($"public delegate void ForEach<{GenericArgs(arity)}>({ForEachParams(arity)});");
        writer.WriteLine($"public delegate void ForEachEntity<{GenericArgs(arity)}>(Entity entity, {ForEachParams(arity)});");
    }

    private static void Ctor(IndentedTextWriter writer) => writer.WriteLine("public Query(World world) : base(world) { }");

    private static void ForEach(IndentedTextWriter writer, int arity)
    {
        writer.WriteLine($"public void ForEach(ForEach<{GenericArgs(arity)}> forEach)");
        writer.WriteLine("{");
        writer.Indent++;
        writer.WriteLine("var matchingArchetypes = GetMatchingArchetypes();");
        writer.WriteLine("foreach (var archetype in matchingArchetypes)");
        writer.WriteLine("{");
        writer.Indent++;
        writer.WriteLine("foreach (var chunk in archetype.Chunks)");
        writer.WriteLine("{");
        writer.Indent++;
        writer.WriteLine("var entityCount = chunk.Count;");
        writer.WriteLine("if (entityCount == 0)");
        writer.Indent++;
        writer.WriteLine("continue;");
        writer.Indent--;
        writer.WriteLine();
        for (var i = 0; i < arity; ++i)
        {
            writer.WriteLine($"var t{i}Column = chunk.GetColumnIndex<T{i}>();");
            writer.WriteLine($"var t{i}Data = (T{i}[])chunk.Columns[t{i}Column];");
            writer.WriteLine();
        }
        writer.WriteLine("for (var i = 0; i < entityCount; ++i)");
        writer.Indent++;
        writer.WriteLine($"forEach({ForEachArgs(arity)});");
        writer.Indent--;
        writer.Indent--;
        writer.WriteLine("}");
        writer.Indent--;
        writer.WriteLine("}");
        writer.Indent--;
        writer.WriteLine("}");
    }

    private static void ForEachEntity(IndentedTextWriter writer, int arity)
    {
        writer.WriteLine($"public void ForEach(ForEachEntity<{GenericArgs(arity)}> forEach)");
        writer.WriteLine("{");
        writer.Indent++;
        writer.WriteLine("var matchingArchetypes = GetMatchingArchetypes();");
        writer.WriteLine("foreach (var archetype in matchingArchetypes)");
        writer.WriteLine("{");
        writer.Indent++;
        writer.WriteLine("foreach (var chunk in archetype.Chunks)");
        writer.WriteLine("{");
        writer.Indent++;
        writer.WriteLine("var entityCount = chunk.Count;");
        writer.WriteLine("if (entityCount == 0)");
        writer.Indent++;
        writer.WriteLine("continue;");
        writer.Indent--;
        writer.WriteLine();
        for (var i = 0; i < arity; ++i)
        {
            writer.WriteLine($"var t{i}Column = chunk.GetColumnIndex<T{i}>();");
            writer.WriteLine($"var t{i}Data = (T{i}[])chunk.Columns[t{i}Column];");
            writer.WriteLine();
        }
        writer.WriteLine("for (var i = 0; i < entityCount; ++i)");
        writer.Indent++;
        writer.WriteLine($"forEach(chunk.Entities[i], {ForEachArgs(arity)});");
        writer.Indent--;
        writer.Indent--;
        writer.WriteLine("}");
        writer.Indent--;
        writer.WriteLine("}");
        writer.Indent--;
        writer.WriteLine("}");
    }

    public static string Join(int count, Func<int, string> func, string separator) => string.Join(separator, Enumerable.Range(0, count).Select(func));

    /// <summary>
    /// Outputs generic type arguments for a given arity.
    /// e.g. for arity 2, outputs "T0, T1"
    /// </summary>
    private static string GenericArgs(int arity) => Join(arity, n => $"T{n}", ", ");

    /// <summary>
    /// Outputs parameters for a given arity.
    /// e.g. for arity 2, outputs "ref T0 t0, ref T1 t1"
    /// </summary>
    private static string ForEachParams(int arity) => Join(arity, n => $"ref T{n} t{n}", ", ");

    private static string ForEachArgs(int arity) => Join(arity, n => $"ref t{n}Data[i]", ", ");
}