<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Arc.Framework\Arc.Framework.csproj"/>
        <ProjectReference Include="..\..\Source\Arc.Ecs.SourceGen\Arc.Ecs.SourceGen\Arc.Ecs.SourceGen.csproj"
                          OutputItemType="Analyzer"
                          ReferenceOutputAssembly="false"/>
        <ProjectReference Include="..\..\Source\Arc.Graphics.D3D11\Arc.Graphics.D3D11.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12"/>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Source\Graphics\2D.hlsl"/>
    </ItemGroup>

</Project>
