<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>

        <!-- Umbrella package: ship no DLL -->
        <IncludeBuildOutput>false</IncludeBuildOutput>
    </PropertyGroup>

    <!--<ItemGroup>
        &lt;!&ndash; The moduyles you want "installed by default" &ndash;&gt;
        <PackageReference Include="Arc.Core" Version="$(Version)"/>
    </ItemGroup>-->

    <ItemGroup>
        <ProjectReference Include="..\Source\Arc.Core\Arc.Core.csproj"/>
        <ProjectReference Include="..\Source\Arc.Ecs\Arc.Ecs.csproj"/>
        <ProjectReference Include="..\Source\Arc.Graphics\Arc.Graphics.csproj" />
        <ProjectReference Include="..\Source\Arc.Platform\Arc.Platform.csproj"/>
        <ProjectReference Include="..\Source\Arc.Runtime\Arc.Runtime.csproj"/>
    </ItemGroup>
</Project>
